### PR TITLE
fix: fix the bug in arc bounds, closed #113

### LINKED ISSUE #113: [bug] arc pick event not work

### PR DESCRIPTION
**Pull request by neuqzxy**
[[中文版模板 / Chinese template](https://github.com/VisActor/vrender/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Workflow
- [ ] Release
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    fix the bug in arc bounds       |
| 🇨🇳 Chinese |     修复arc bounds的bug      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: packages/vrender/src/graphic/graphic-service/graphic-service.ts [hunk 1]
```diff
@@ -1305,14 +1305,14 @@ export class DefaultGraphicService implements IGraphicService {
...
-      innerRadius = arcTheme.innerRadius,
-      endAngle = arcTheme.endAngle,
-      startAngle = arcTheme.startAngle
-    } = attribute;
+    const { outerRadius = arcTheme.outerRadius, innerRadius = arcTheme.innerRadius } = attribute;
+    let { endAngle = arcTheme.endAngle, startAngle = arcTheme.startAngle } = attribute;
 
-    // const { startAngle, endAngle } = this.getParsedAngle();
+    if (startAngle > endAngle) {
+      const temp = startAngle;
```
Comment (xile611) [inline packages/vrender/src/graphic/graphic-service/graphic-service.ts:1312]: we call use the next line to switch two vars:
```[startAngle, endAngle] = [endAngle, startAngle];```

Comment (neuqzxy) [reply packages/vrender/src/graphic/graphic-service/graphic-service.ts:1312]: this  may cause performance issues because of array deconstruction in some packaging Configuration

**Review by Rui-Sun — APPROVED** [review]
